<?php

namespace App\Support;

class BoardIcons
{
    /**
     * Template word label (lowercase) => catalog key stored on words.icon.
     *
     * @var array<string, string>
     */
    private const WORDS = [
        'me' => 'LookTopIcon',
        'myself' => 'LookTopIcon',
        'my' => 'Hold02Icon',
        'finished' => 'BookmarkCheck01Icon',
        'want' => 'FavouriteIcon',
        'need' => 'Alert01Icon',
        'please' => 'Clapping01Icon',
        'help' => 'HelpCircleIcon',
        'yes' => 'Tick01Icon',
        'no' => 'Cancel01Icon',
        'more' => 'Add01Icon',
        'done' => 'TaskDone01Icon',
        'the' => 'SecondBracketIcon',
        'is' => 'ApproximatelyEqualSquareIcon',
        'it' => 'EqualSignSquareIcon',
        'that' => 'PointingLeft02Icon',
        'what' => 'Quiz01Icon',
        'on' => 'RotateLeft04Icon',
        'in' => 'LoginCircle01Icon',
        'here' => 'Location04Icon',
        'out' => 'LogoutCircle01Icon',
        'off' => 'RotateRight04Icon',
        'some' => 'SignLanguageCIcon',
        'you' => 'UserIdVerificationIcon',
        'go' => 'ArrowRight01Icon',
        'hungry' => 'DroolingIcon',
        'thirsty' => 'DroolingIcon',
        'eat' => 'SpoonAndForkIcon',
        'snack' => 'CookieIcon',
        'breakfast' => 'Bread01Icon',
        'lunch' => 'ServingFoodIcon',
        'dinner' => 'PlateIcon',
        'meal' => 'VegetarianFoodIcon',
        'food' => 'StreetFoodIcon',
        'cook' => 'BbqGrillIcon',
        'cookie' => 'BiscuitIcon',
        'candy' => 'CandyIcon',
        'corn' => 'CornIcon',
        'bean' => 'BeanIcon',
        'cup' => 'CupSodaIcon',
        'drink' => 'CupSodaIcon',
        'apple' => 'Apple01Icon',
        'pie' => 'ApplePieIcon',
        'banana' => 'BananaIcon',
        'chicken' => 'ChickenThighsIcon',
        'cheese' => 'CheeseIcon',
        'cake' => 'CakeIcon',
        'water' => 'GlassWaterIcon',
        'juice' => 'SoftDrink01Icon',
        'milk' => 'MilkBottleIcon',
        'coffee' => 'Coffee01Icon',
        'tea' => 'BubbleTea01Icon',
        'happy' => 'Happy01Icon',
        'sad' => 'Sad01Icon',
        'tired' => 'Tired01Icon',
        'mad' => 'AngryIcon',
        'scared' => 'GhostIcon',
        'hurt' => 'BandageIcon',
        'okay' => 'ThumbsUpIcon',
        'mom' => 'WomanIcon',
        'dad' => 'ManIcon',
        'baby' => 'Baby02Icon',
        'boy' => 'ManIcon',
        'girl' => 'WomanIcon',
        'man' => 'ManIcon',
        'woman' => 'WomanIcon',
        'he' => 'ManIcon',
        'him' => 'ManIcon',
        'his' => 'ManIcon',
        'she' => 'WomanIcon',
        'her' => 'WomanIcon',
        'we' => 'ManWomanIcon',
        'us' => 'ManWomanIcon',
        'people' => 'UserGroupIcon',
        'name' => 'HandHelpingIcon',
        'teacher' => 'TeacherIcon',
        'doctor' => 'Doctor01Icon',
        'hi' => 'WavingHand01Icon',
        'hello' => 'WavingHand01Icon',
        'bye' => 'WavingHand02Icon',
        'home' => 'House05Icon',
        'house' => 'House05Icon',
        'school' => 'SchoolIcon',
        'outside' => 'Sun03Icon',
        'bathroom' => 'Toilet01Icon',
        'toilet' => 'Toilet01Icon',
        'store' => 'Store01Icon',
        'park' => 'PineTreeIcon',
        'beach' => 'BeachIcon',
        'hill' => 'MountainIcon',
        'side' => 'SidebarLeft01Icon',
        'middle' => 'TextCenterlineMiddleIcon',
        'top' => 'TextCenterlineCenterTopIcon',
        'door' => 'DoorIcon',
        'bed' => 'BedIcon',
        'chair' => 'Chair05Icon',
        'table' => 'Table02Icon',
        'couch' => 'Sofa02Icon',
        'sink' => 'Sink01Icon',
        'stop' => 'StopIcon',
        'come' => 'HandIcon',
        'look' => 'ViewIcon',
        'wait' => 'Clock01Icon',
        'play' => 'PlayIcon',
        'sleep' => 'SleepingIcon',
        'buy' => 'ShoppingCartAdd02Icon',
        'call' => 'SpeechIcon',
        'cut' => 'VoucherIcon',
        'fall' => 'FallingStarIcon',
        'find' => 'SearchFocusIcon',
        'fix' => 'RepairIcon',
        'fly' => 'AirplaneTakeOff01Icon',
        'found' => 'SearchFocusIcon',
        'get' => 'AlmsIcon',
        'give' => 'HandCoinsIcon',
        'going' => 'Logout03Icon',
        'hear' => 'EarIcon',
        'hold' => 'HoldPhoneIcon',
        'jump' => 'SkippingRopeIcon',
        'know' => 'BrainIcon',
        'lift' => 'ArrowsUpFromLineIcon',
        'move' => 'MoveIcon',
        'open' => 'PackageOpenIcon',
        'paint' => 'PaintBucketIcon',
        'pick' => 'CursorPointer01Icon',
        'push' => 'CharityIcon',
        'remember' => 'AiIdeaIcon',
        'ride' => 'RollerCoasterIcon',
        'run' => 'WorkoutRunIcon',
        'said' => 'SpeechIcon',
        'saw' => 'EyeIcon',
        'say' => 'SpeechIcon',
        'see' => 'EyeIcon',
        'show' => 'Hold05Icon',
        'shut' => 'DoorClosedIcon',
        'sit' => 'WorkoutSquatsIcon',
        'tell' => 'SpeechIcon',
        'turn' => 'ArrowTurnBackwardIcon',
        'bad' => 'ThumbsDownIcon',
        'different' => 'ThumbsUpDownIcon',
        'first' => 'ChevronFirstIcon',
        'last' => 'ChevronLastIcon',
        'good' => 'ThumbsUpIcon',
        'great' => 'ThumbsUpEllipseIcon',
        'hot' => 'HeaterIcon',
        'new' => 'NewReleasesIcon',
        'ready' => 'CheckLineIcon',
        'right' => 'ArrowBigRightDashIcon',
        'left' => 'ArrowBigLeftDashIcon',
        'up' => 'ArrowBigUpDashIcon',
        'down' => 'ArrowBigDownDashIcon',
        'well' => 'HealthIcon',
        'whole' => 'CircleIcon',
        'ball' => 'YogaBallIcon',
        'toy' => 'ToyTrainIcon',
        'piece' => 'PuzzleIcon',
        'thing' => 'GroupItemsIcon',
        'tape' => 'TapeMeasureIcon',
        'car' => 'Car03Icon',
        'truck' => 'TruckMonsterIcon',
        'motorcycle' => 'Motorbike01Icon',
        'bicycle' => 'BicycleIcon',
        'bus' => 'Bus03Icon',
        'golf cart' => 'GolfCartIcon',
        'tree' => 'Tree01Icon',
        'leaf' => 'Leaf01Icon',
        'fire' => 'FireIcon',
        'day' => 'Sun03Icon',
        'night' => 'Moon02Icon',
        'time' => 'Time02Icon',
        'today' => 'Calendar04Icon',
        'again' => 'ReplayIcon',
        'almost' => 'ApproximatelyEqualIcon',
        'never' => 'TrapezoidLineVerticalIcon',
        'next' => 'NextIcon',
        'face' => 'CrazyIcon',
        'finger' => 'CursorPointer02Icon',
        'hair' => 'HairClipsIcon',
        'hand' => 'HandIcon',
        'head' => 'Brain02Icon',
        'shoulder' => 'ShoulderIcon',
        'back' => 'BackMuscleBodyIcon',
        'muscle' => 'BicepsFlexedIcon',
        'leg' => 'BodyPartLegIcon',
        'red' => 'CircleIcon',
        'orange' => 'CircleIcon',
        'yellow' => 'CircleIcon',
        'green' => 'CircleIcon',
        'blue' => 'CircleIcon',
        'purple' => 'CircleIcon',
        'pink' => 'CircleIcon',
        'black' => 'CircleIcon',
        'white' => 'CircleIcon',
        'brown' => 'CircleIcon',
        'circle' => 'CircleIcon',
        'square' => 'Square01Icon',
        'triangle' => 'Triangle01Icon',
        'rectangle' => 'PulseRectangle01Icon',
        'star' => 'StarIcon',
        'heart' => 'HeartIcon',
        'oval' => 'OvalIcon',
        'diamond' => 'Diamond01Icon',
        'bird' => 'BirdIcon',
        'bug' => 'Bug01Icon',
        'dog' => 'Bone01Icon',
        'duck' => 'RubberDuckIcon',
        'horse' => 'HorseIcon',
        'i' => 'lucide:smile',
        'mine' => 'lucide:smile-plus',
        'friend' => 'lucide:users-round',
    ];

    /**
     * Template folder name => catalog key stored on menus.icon.
     *
     * @var array<string, string>
     */
    private const FOLDERS = [
        'Animals' => 'PokemonIcon',
        'Body' => 'UserFullViewIcon',
        'Colors' => 'RainbowIcon',
        'Describing' => 'FolderDetailsIcon',
        'Feelings' => 'MaskTheater01Icon',
        'Food' => 'ServingFoodIcon',
        'Friends' => 'UserGroupIcon',
        'Home' => 'House05Icon',
        'Nature' => 'Image03Icon',
        'Numbers' => 'ArrangeByNumbersOneNineIcon',
        'Places' => 'BeachIcon',
        'Really' => 'ExclamationMarkBigIcon',
        'Shapes' => 'DiceIcon',
        'Stuff' => 'GroupItemsIcon',
        'Time' => 'Time02Icon',
        'Vehicles' => 'GarbageTruckIcon',
    ];

    public static function forWord(string $label): ?string
    {
        return self::WORDS[strtolower(trim($label))] ?? null;
    }

    public static function forFolder(string $name): ?string
    {
        return self::FOLDERS[trim($name)] ?? null;
    }
}
